services:
  Shared.Logger:
    class:  ../../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Shared.ConnectionManager:
    factory:
      class:  ../../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
      arguments: ['mooc']