services:
  Shared.Logger:
    class:  ../../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Shared.ConnectionManager:
    factory:
      class:  ../../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
      arguments: ['mooc']

  Shared.QueryHandlersInformation:
    class: ../../../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlersInformation
    arguments: ['!tagged queryHandler']

  Shared.QueryBus:
    class: ../../../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Shared.QueryHandlersInformation']