services:
  Mooc.Courses.domain.CourseRepository:
    class: ../../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@Backoffice.Shared.ConnectionManager']

  Mooc.Courses.application.CourseCreator:
    class: ../../../../../Contexts/Mooc/Courses/application/Create/CourseCreator
    arguments: ['@Mooc.Courses.domain.CourseRepository', '@Backoffice.Shared.domain.EventBus']

  Mooc.courses.CreateCourseCommandHandler:
    class: ../../../../../Contexts/Mooc/Courses/application/Create/CreateCourseCommandHandler
    arguments: ['@Mooc.Courses.application.CourseCreator']
    tags:
      - { name: 'commandHandler' }

  Backoffice.Courses.application.CoursesFinder:
    class: ../../../../../Contexts/Backoffice/Courses/application/SearchAll/CoursesFinder
    arguments: ['@Backoffice.Courses.domain.BackofficeCourseRepository']

  Backoffice.courses.SearchAllCoursesQueryHandler:
    class: ../../../../../Contexts/Backoffice/Courses/application/SearchAll/SearchAllCoursesQueryHandler
    arguments: ['@Backoffice.Courses.application.CoursesFinder']
    tags:
      - { name: 'queryHandler' }

  Backoffice.Courses.domain.BackofficeCourseRepository:
    class: ../../../../../Contexts/Backoffice/Courses/infrastructure/persistence/ElasticBackofficeCourseRepository
    arguments: ['@Backoffice.Shared.ElasticConnectionManager', '@Backoffice.Shared.ElasticConfig']

  Backoffice.Courses.application.BackofficeCourseCreator:
    class: ../../../../../Contexts/Backoffice/Courses/application/Create/BackofficeCourseCreator
    arguments: ['@Backoffice.Courses.domain.BackofficeCourseRepository']

  Backoffice.courses.CreateBackofficeCourseOnCourseCreated:
    class: ../../../../../Contexts/Backoffice/Courses/application/Create/CreateBackofficeCourseOnCourseCreated
    arguments: ['@Backoffice.Courses.application.BackofficeCourseCreator']
    tags:
      - { name: 'domainEventSubscriber' }

  Backoffice.courses.application.CoursesByCriteriaSearcher:
    class: ../../../../../Contexts/Backoffice/Courses/application/SearchByCriteria/CoursesByCriteriaSearcher
    arguments: ['@Backoffice.Courses.domain.BackofficeCourseRepository']

  Backoffice.courses.SearchCoursesByCriteriaQueryHandler:
    class: ../../../../../Contexts/Backoffice/Courses/application/SearchByCriteria/SearchCoursesByCriteriaQueryHandler
    arguments: ['@Backoffice.courses.application.CoursesByCriteriaSearcher']
    tags:
      - { name: 'queryHandler' }