services:

  Apps.mooc.controllers.CoursePutController:
    class: ../../../controllers/CoursePutController
    arguments: ["@Shared.CommandBus"]

  Apps.mooc.controllers.StatusGetController:
    class: ../../../controllers/StatusGetController
    arguments: []

  Apps.mooc.controllers.CoursesCounterGetController:
    class: ../../../controllers/CoursesCounterGetController
    arguments: ["@Shared.QueryBus"]

  Apps.mooc.controllers.CourseGetController:
    class: ../../../controllers/CourseGetController
    arguments: ["@Shared.QueryBus"]