services:

  Apps.mooc.controllers.CoursePutController:
    class: ../../../controllers/CoursePutController
    arguments: ["@Shared.CommandBus"]

  Apps.mooc.controllers.CourseRenameController:
    class: ../../../controllers/CourseRenameController
    arguments: ["@Shared.CommandBus"]

  Apps.mooc.controllers.StatusGetController:
    class: ../../../controllers/StatusGetController
    arguments: []

  Apps.mooc.controllers.CoursesCounterGetController:
    class: ../../../controllers/CoursesCounterGetController
    arguments: ["@Shared.QueryBus"]

  Apps.mooc.controllers.CourseGetController:
    class: ../../../controllers/CourseGetController
    arguments: ["@Shared.QueryBus"]

  Apps.mooc.controllers.CoursesGetController:
    class: ../../../controllers/CoursesGetController
    arguments: ["@Shared.QueryBus"]

  Apps.mooc.controllers.CourseLikePostController:
    class: ../../../controllers/CourseLikePostController
    arguments: ["@Shared.CommandBus"]