imports:
  - { resource: ./application.yaml }

services:
  Backoffice.EnvironmentArranger:
    class: ../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Backoffice.Shared.ConnectionManager']