imports:
  - { resource: ./application.yaml }

services:
  Backoffice.Backend.EnvironmentArranger:
    class: ../../../../../../tests/Contexts/Shared/infrastructure/mongo/MongoEnvironmentArranger
    arguments: ['@Shared.ConnectionManager']