services:

  Mooc.courses.CourseRepository:
    class: ../../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@Shared.ConnectionManager']

  Mooc.courses.CourseCreator:
    class: ../../../../../Contexts/Mooc/Courses/application/CreateCourse/CourseCreator
    arguments: ['@Mooc.courses.CourseRepository', '@Shared.EventBus']

  Mooc.courses.CreateCourseCommandHandler:
    class: ../../../../../Contexts/Mooc/Courses/application/CreateCourse/CreateCourseCommandHandler
    arguments: ['@Mooc.courses.CourseCreator']
    tags:
      - { name: 'commandHandler' }

  Mooc.courses.DomainCourseFinder:
    class: ../../../../../Contexts/Mooc/Courses/domain/CourseFinder
    arguments: ["@Mooc.courses.CourseRepository"]

  Mooc.courses.CourseFinder:
    class: ../../../../../Contexts/Mooc/Courses/application/GetCourse/CourseFinder
    arguments: ["@Mooc.courses.DomainCourseFinder"]

  Mooc.courses.GetCourseQueryHandler:
    class: ../../../../../Contexts/Mooc/Courses/application/GetCourse/GetCourseQueryHandler
    arguments: ["@Mooc.courses.CourseFinder"]
    tags:
      - { name: 'queryHandler' }

  Mooc.courses.CourseRenamer:
    class: ../../../../../Contexts/Mooc/Courses/application/RenameCourse/CourseRenamer
    arguments: ["@Mooc.courses.DomainCourseFinder", "@Mooc.courses.CourseRepository", "@Shared.EventBus"]

  Mooc.courses.RenameCourseCommandHandler:
    class: ../../../../../Contexts/Mooc/Courses/application/RenameCourse/RenameCourseCommandHandler
    arguments: ['@Mooc.courses.CourseRenamer']
    tags:
      - { name: 'commandHandler' }

  Mooc.courses.CoursesSearcher:
    class: ../../../../../Contexts/Mooc/Courses/application/GetCourses/CoursesSearcher
    arguments: ["@Mooc.courses.CourseRepository"]

  Mooc.courses.GetCoursesQueryHandler:
    class: ../../../../../Contexts/Mooc/Courses/application/GetCourses/GetCoursesQueryHandler
    arguments: ["@Mooc.courses.CoursesSearcher"]
    tags:
      - { name: 'queryHandler' }

  Mooc.courses.CourseLiker:
    class: ../../../../../Contexts/Mooc/Courses/application/LikeCourse/CourseLiker
    arguments: ["@Mooc.courses.DomainCourseFinder", "@Mooc.courses.CourseRepository"]

  Mooc.courses.LikeCourseCommandHandler:
    class: ../../../../../Contexts/Mooc/Courses/application/LikeCourse/LikeCourseCommandHandler
    arguments: ['@Mooc.courses.CourseLiker']
    tags:
      - { name: 'commandHandler' }

