services:

  Mooc.courses.CourseRepository:
    class: ../../../../../Contexts/Mooc/Courses/infrastructure/persistence/MongoCourseRepository
    arguments: ['@Shared.ConnectionManager']

  Mooc.courses.CourseCreator:
    class: ../../../../../Contexts/Mooc/Courses/application/CreateCourse/CourseCreator
    arguments: ['@Mooc.courses.CourseRepository', '@Shared.EventBus']

  Mooc.courses.CreateCourseCommandHandler:
    class: ../../../../../Contexts/Mooc/Courses/application/CreateCourse/CreateCourseCommandHandler
    arguments: ['@Mooc.courses.CourseCreator']
    tags:
      - { name: 'commandHandler' }

  Mooc.courses.CourseFinder:
    class: ../../../../../Contexts/Mooc/Courses/application/GetCourse/CourseFinder
    arguments: ["@Mooc.courses.CourseRepository"]

  Mooc.courses.GetCourseQueryHandler:
    class: ../../../../../Contexts/Mooc/Courses/application/GetCourse/GetCourseQueryHandler
    arguments: ["@Mooc.courses.CourseFinder"]
    tags:
      - { name: 'queryHandler' }