name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: make deps

      - name: Compile TypeScript
        run: make compile

      - name: Start all the environment
        run: make start

      - name: Wait for the environment to get up
        run: |
          while ! make ping-mysql &>/dev/null; do
              echo "Waiting for database connection..."
              sleep 2
          done

      - name: Run the tests
        run: make test
